
package com.tang.crm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.tang.com/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.tang.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDzIdByAddress", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindDzIdByAddress")
    @ResponseWrapper(localName = "findDzIdByAddressResponse", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindDzIdByAddressResponse")
    public String findDzIdByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tang.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAssociation", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindAssociation")
    @ResponseWrapper(localName = "findAssociationResponse", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindAssociationResponse")
    public List<Customer> findAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tang.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTele", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindByTele")
    @ResponseWrapper(localName = "findByTeleResponse", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindByTeleResponse")
    public Customer findByTele(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.tang.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssociation", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindNotAssociation")
    @ResponseWrapper(localName = "findNotAssociationResponse", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.FindNotAssociationResponse")
    public List<Customer> findNotAssociation();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "ass", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.Ass")
    @ResponseWrapper(localName = "assResponse", targetNamespace = "http://service.crm.tang.com/", className = "com.tang.crm.service.AssResponse")
    public void ass(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

}
